import Api from '../api/apiMoch';

const useMoch = () => {
  Api.post('/auth/token', {
    access_token: 'ebdsjcdkosoqe3r4gnfvnwoe2g94nvsjka23f0vslvnsk39jsncje239',
    permission: {},
  });
  Api.post('/auth/forget_password/send_verification', {});
  Api.post('/auth/forget_password/verify_reset_code', {});
  Api.post('/auth/forget_password/reset_password', {});
  Api.get('/patients', {
    patients_list_data: [
      {
        member_id: '2015632',
        enroll_date: '2026/10/10',
        score: '60',
        last_followup: '2026/7/10',
        picture: '',
        name: 'my name is test for test this is  along name very long name',
        status: 'Needs Check',
        age: 27,
        progress: 60,
        sex: 'Male',
        email: 'moch@moch.com',
        weight: 80,
        favorite: false,
        archived: false,
        drift_analyzed: false,
        assigned_to: ['amir this is amir is a good man'],
        'Check-in': [
          'amir this is amir is a good man',
          'amir this is amir is a good man',
        ],
        Questionary: 'this is questioanray',
      },
      {
        member_id: '2015632',
        enroll_date: '2026/10/10',
        score: '60',
        last_followup: '2026/7/10',
        picture: '',
        name: 'my name is test for test this is  along name very long name',
        status: 'Needs Check',
        age: 27,
        has_minimum_data: true,
        progress: 60,
        sex: 'Male',
        email: 'moch@moch.com',
        weight: 80,
        favorite: true,
        archived: false,
        drift_analyzed: false,
        assigned_to: ['amir this is amir is a good man'],
        'Check-in': [
          'amir this is amir is a good man',
          'amir this is amir is a good man',
        ],
        Questionary: 'this is questioanray',
        'Latest Sync': '2026-1-14',
        last_checkin: '2026-1-5',
      },
      {
        member_id: '2015632',
        enroll_date: '2026/10/10',
        score: '60',
        last_followup: '2026/7/10',
        picture: '',
        name: 'my name is test for test this is  along name very long name',
        status: 'Needs Check',
        age: 27,
        has_minimum_data: true,
        progress: 60,
        sex: 'Male',
        email: 'moch@moch.com',
        weight: 80,
        favorite: true,
        archived: false,
        drift_analyzed: false,
        assigned_to: ['amir this is amir is a good man'],
        'Check-in': [
          'amir this is amir is a good man',
          'amir this is amir is a good man',
        ],
        Questionary: 'this is questioanray',
        'Latest Sync': '2026-1-14',
        last_checkin: '2026-1-5',
      },
      {
        member_id: '2015632',
        enroll_date: '2026/10/10',
        score: '60',
        last_followup: '2026/7/10',
        picture: '',
        name: 'my name is test for test this is  along name very long name',
        status: 'Needs Check',
        age: 27,
        has_minimum_data: true,
        progress: 60,
        sex: 'Male',
        email: 'moch@moch.com',
        weight: 80,
        favorite: true,
        archived: false,
        drift_analyzed: false,
        assigned_to: ['amir this is amir is a good man'],
        'Check-in': [
          'amir this is amir is a good man',
          'amir this is amir is a good man',
        ],
        Questionary: 'this is questioanray',
        'Latest Sync': '2026-1-14',
        last_checkin: '2026-1-5',
      },
      {
        member_id: '2015632',
        enroll_date: '2026/10/10',
        score: '60',
        last_followup: '2026/7/10',
        picture: '',
        name: 'my name is test for test this is  along name very long name',
        status: 'Needs Check',
        age: 27,
        has_minimum_data: true,
        progress: 60,
        sex: 'Male',
        email: 'moch@moch.com',
        weight: 80,
        favorite: true,
        archived: false,
        drift_analyzed: false,
        assigned_to: ['amir this is amir is a good man'],
        'Check-in': [
          'amir this is amir is a good man',
          'amir this is amir is a good man',
        ],
        Questionary: 'this is questioanray',
        'Latest Sync': '2026-1-14',
        last_checkin: '2026-1-5',
      },
      {
        member_id: '2015632',
        enroll_date: '2026/10/10',
        score: '60',
        last_followup: '2026/7/10',
        picture: '',
        name: 'my name is test for test this is  along name very long name',
        status: 'Needs Check',
        age: 27,
        has_minimum_data: true,
        progress: 60,
        sex: 'Male',
        email: 'moch@moch.com',
        weight: 80,
        favorite: true,
        archived: false,
        drift_analyzed: false,
        assigned_to: ['amir this is amir is a good man'],
        'Check-in': [
          'amir this is amir is a good man',
          'amir this is amir is a good man',
        ],
        Questionary: 'this is questioanray',
        'Latest Sync': '2026-1-14',
        last_checkin: '2026-1-5',
      },
      {
        member_id: '2015632',
        enroll_date: '2026/10/10',
        score: '60',
        last_followup: '2026/7/10',
        picture: '',
        name: 'my name is test for test this is  along name very long name',
        status: 'Needs Check',
        age: 27,
        has_minimum_data: true,
        progress: 60,
        sex: 'Male',
        email: 'moch@moch.com',
        weight: 80,
        favorite: true,
        archived: false,
        drift_analyzed: false,
        assigned_to: ['amir this is amir is a good man'],
        'Check-in': [
          'amir this is amir is a good man',
          'amir this is amir is a good man',
        ],
        Questionary: 'this is questioanray',
        'Latest Sync': '2026-1-14',
        last_checkin: '2026-1-5',
      },
      {
        member_id: '2015632',
        enroll_date: '2026/10/10',
        score: '60',
        last_followup: '2026/7/10',
        picture: '',
        name: 'my name is test for test this is  along name very long name',
        status: 'Needs Check',
        age: 27,
        has_minimum_data: true,
        progress: 60,
        sex: 'Male',
        email: 'moch@moch.com',
        weight: 80,
        favorite: true,
        archived: false,
        drift_analyzed: false,
        assigned_to: ['amir this is amir is a good man'],
        'Check-in': [
          'amir this is amir is a good man',
          'amir this is amir is a good man',
        ],
        Questionary: 'this is questioanray',
        'Latest Sync': '2026-1-14',
        last_checkin: '2026-1-5',
      },
      {
        member_id: '2015632',
        enroll_date: '2026/10/10',
        score: '60',
        last_followup: '2026/7/10',
        picture: '',
        name: 'my name is test for test this is  along name very long name',
        status: 'Needs Check',
        age: 27,
        has_minimum_data: true,
        progress: 60,
        sex: 'Male',
        email: 'moch@moch.com',
        weight: 80,
        favorite: true,
        archived: false,
        drift_analyzed: false,
        assigned_to: ['amir this is amir is a good man'],
        'Check-in': [
          'amir this is amir is a good man',
          'amir this is amir is a good man',
        ],
        Questionary: 'this is questioanray',
        'Latest Sync': '2026-1-14',
        last_checkin: '2026-1-5',
      },
      {
        member_id: '2015632',
        enroll_date: '2026/10/10',
        score: '60',
        last_followup: '2026/7/10',
        picture: '',
        name: 'my name is test for test this is  along name very long name',
        status: 'Needs Check',
        age: 27,
        has_minimum_data: true,
        progress: 60,
        sex: 'Male',
        email: 'moch@moch.com',
        weight: 80,
        favorite: true,
        archived: false,
        drift_analyzed: false,
        assigned_to: ['amir this is amir is a good man'],
        'Check-in': [
          'amir this is amir is a good man',
          'amir this is amir is a good man',
        ],
        Questionary: 'this is questioanray',
        'Latest Sync': '2026-1-14',
        last_checkin: '2026-1-5',
      },
      {
        member_id: '2015632',
        enroll_date: '2026/10/10',
        score: '60',
        last_followup: '2026/7/10',
        picture: '',
        name: 'my name is test for test this is  along name very long name',
        status: 'Needs Check',
        age: 27,
        has_minimum_data: true,
        progress: 60,
        sex: 'Male',
        email: 'moch@moch.com',
        weight: 80,
        favorite: true,
        archived: false,
        drift_analyzed: false,
        assigned_to: ['amir this is amir is a good man'],
        'Check-in': [
          'amir this is amir is a good man',
          'amir this is amir is a good man',
        ],
        Questionary: 'this is questioanray',
        'Latest Sync': '2026-1-14',
        last_checkin: '2026-1-5',
      },
      {
        member_id: '2015632',
        enroll_date: '2026/10/10',
        score: '60',
        last_followup: '2026/7/10',
        picture: '',
        name: 'my name is test for test this is  along name very long name',
        status: 'Needs Check',
        age: 27,
        has_minimum_data: true,
        progress: 60,
        sex: 'Male',
        email: 'moch@moch.com',
        weight: 80,
        favorite: true,
        archived: false,
        drift_analyzed: false,
        assigned_to: ['amir this is amir is a good man'],
        'Check-in': [
          'amir this is amir is a good man',
          'amir this is amir is a good man',
        ],
        Questionary: 'this is questioanray',
        'Latest Sync': '2026-1-14',
        last_checkin: '2026-1-5',
      },
    ],
  });
};

export default useMoch;
